version: "3"
services:
  nestjs-base-template:
    container_name: nestjs-base-template
    image: nestjs-base-template:local
    build:
      context: ./
      dockerfile: ./deployments/docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm i && npm run start:dev"
    env_file:
      - ./env/.env

  mongo:
    container_name: mongo
    image: mongo:4.4.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: nestjs-base-template
      DB_NAME: nestjs-base-template
      DB_USER: root
      DB_PASSWORD: root

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
